# Generated by Django 3.0.8 on 2020-11-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20201028_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Clients',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
