# Generated by Django 3.0.8 on 2020-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20201104_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summery', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
